// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KWLTtVquGJsmdvysZZJO3UzD-FVoga8',
    appId: '1:1099021040898:web:4fcabbd08ed4678e24161b',
    messagingSenderId: '1099021040898',
    projectId: 'manuschool-58036',
    authDomain: 'manuschool-58036.firebaseapp.com',
    storageBucket: 'manuschool-58036.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_32VKZW1NFLVNfciEwGuBWvwAkZycT0o',
    appId: '1:1099021040898:android:c0474c7c7e4e84cf24161b',
    messagingSenderId: '1099021040898',
    projectId: 'manuschool-58036',
    storageBucket: 'manuschool-58036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjuwq493hwqAopzbzneb6U93CQVQ3cx-s',
    appId: '1:1099021040898:ios:4bf94244a757639724161b',
    messagingSenderId: '1099021040898',
    projectId: 'manuschool-58036',
    storageBucket: 'manuschool-58036.firebasestorage.app',
    iosBundleId: 'com.example.trueHostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjuwq493hwqAopzbzneb6U93CQVQ3cx-s',
    appId: '1:1099021040898:ios:4bf94244a757639724161b',
    messagingSenderId: '1099021040898',
    projectId: 'manuschool-58036',
    storageBucket: 'manuschool-58036.firebasestorage.app',
    iosBundleId: 'com.example.trueHostelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6KWLTtVquGJsmdvysZZJO3UzD-FVoga8',
    appId: '1:1099021040898:web:920626eb2e2b829f24161b',
    messagingSenderId: '1099021040898',
    projectId: 'manuschool-58036',
    authDomain: 'manuschool-58036.firebaseapp.com',
    storageBucket: 'manuschool-58036.firebasestorage.app',
  );
}
