import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'core/theme/app_theme.dart';
import 'core/utils/tenant_config.dart';
import 'presentation/views/auth/login_view.dart';
import 'firebase_options.dart'; // Automatically generated by FlutterFire CLI setup

void main() async {
  // Ensuring native UI rendering layer engine hooks are verified before running async services
  WidgetsFlutterBinding.ensureInitialized();
  
  // Automated Firebase configuration handshake initialized with Multi-Platform Core Options Matrix
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Bootstrapping the application tree scoped securely inside Riverpod infrastructure mapping container
  runApp(
    const ProviderScope(
      child: TrueHostelApp(),
    ),
  );
}

class TrueHostelApp extends StatelessWidget {
  const TrueHostelApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Gathering whitelabel support details mapping back to opnora.com network parameters
    final tenant = TenantConfig.fromEnvironment();

    return MaterialApp(
      title: tenant.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.light, // Default daylight execution parameters matrix active
      // Launch gate explicitly routing incoming streams directly through dynamic multi-tenant authentication
      home: const LoginView(),
    );
  }
}